"""initial schema

Revision ID: 1a40328e7aab
Revises: 
Create Date: 2026-07-17 19:33:36.744423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1a40328e7aab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_bars',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'ts', 'source', name='uq_bar')
    )
    op.create_index('ix_bars_symbol_tf_ts', 'market_bars', ['symbol', 'timeframe', 'ts'], unique=False)
    op.create_table('model_versions',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('artifact', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('training_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_version')
    )
    op.create_table('position_snapshots',
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('equity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cash', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('positions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_possnap_env_created', 'position_snapshots', ['environment', 'created_at'], unique=False)
    op.create_table('promotion_events',
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=False),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('class_path', sa.String(length=256), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_strategy_version')
    )
    op.create_table('system_controls',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('experiments',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('champion_model_id', sa.Uuid(), nullable=True),
    sa.Column('challenger_model_id', sa.Uuid(), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenger_model_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['champion_model_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_reports',
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=True),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('regime', sa.String(length=32), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_perf_strategy_period', 'performance_reports', ['strategy_id', 'period_start', 'period_end'], unique=False)
    op.create_table('signals',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_reason', sa.String(length=256), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('signal_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'dedupe_key', name='uq_signal_dedupe')
    )
    op.create_index('ix_signals_symbol_created', 'signals', ['symbol', 'created_at'], unique=False)
    op.create_table('decisions',
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=True),
    sa.Column('model_version_id', sa.Uuid(), nullable=True),
    sa.Column('signal_id', sa.Uuid(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk_verdict', sa.String(length=16), nullable=True),
    sa.Column('risk_detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('outcome', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('outcome_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_mode_status', 'decisions', ['mode', 'status'], unique=False)
    op.create_index('ix_decisions_strategy_created', 'decisions', ['strategy_id', 'created_at'], unique=False)
    op.create_table('orders',
    sa.Column('decision_id', sa.Uuid(), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('time_in_force', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('status_reason', sa.String(length=512), nullable=True),
    sa.Column('filled_qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('filled_avg_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_broker_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id', name='uq_client_order_id')
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index('ix_orders_env_status', 'orders', ['environment', 'status'], unique=False)
    op.create_index('ix_orders_symbol_created', 'orders', ['symbol', 'created_at'], unique=False)
    op.create_table('risk_events',
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('environment', sa.String(length=8), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_events_rule_created', 'risk_events', ['rule', 'created_at'], unique=False)
    op.create_table('fills',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('broker_fill_id', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'broker_fill_id', name='uq_fill_dedupe')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fills')
    op.drop_index('ix_risk_events_rule_created', table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index('ix_orders_symbol_created', table_name='orders')
    op.drop_index('ix_orders_env_status', table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_decisions_strategy_created', table_name='decisions')
    op.drop_index('ix_decisions_mode_status', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_signals_symbol_created', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_perf_strategy_period', table_name='performance_reports')
    op.drop_table('performance_reports')
    op.drop_table('experiments')
    op.drop_table('system_controls')
    op.drop_table('strategies')
    op.drop_table('promotion_events')
    op.drop_index('ix_possnap_env_created', table_name='position_snapshots')
    op.drop_table('position_snapshots')
    op.drop_table('model_versions')
    op.drop_index('ix_bars_symbol_tf_ts', table_name='market_bars')
    op.drop_table('market_bars')
    # ### end Alembic commands ###
